// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UINewTabGoogleChromeWindow UINewTabGoogleChromeWindow
        {
            get
            {
                if ((this.mUINewTabGoogleChromeWindow == null))
                {
                    this.mUINewTabGoogleChromeWindow = new UINewTabGoogleChromeWindow();
                }
                return this.mUINewTabGoogleChromeWindow;
            }
        }
        
        public UIMercuryHealthMercuryWindow UIMercuryHealthMercuryWindow
        {
            get
            {
                if ((this.mUIMercuryHealthMercuryWindow == null))
                {
                    this.mUIMercuryHealthMercuryWindow = new UIMercuryHealthMercuryWindow();
                }
                return this.mUIMercuryHealthMercuryWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINewTabGoogleChromeWindow mUINewTabGoogleChromeWindow;
        
        private UIMercuryHealthMercuryWindow mUIMercuryHealthMercuryWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINewTabGoogleChromeWindow : WinWindow
    {
        
        public UINewTabGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "New Tab - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("New Tab - Google Chrome");
            this.WindowTitles.Add("Bing - Google Chrome");
            this.WindowTitles.Add("microsoft - Bing - Google Chrome");
            this.WindowTitles.Add("Microsoft Store Online - Welcome - Google Chrome");
            this.WindowTitles.Add("Xbox: Xbox One and Xbox One S Consoles, Games & Accessories |-Microsoft Store - G" +
                    "oogle Chrome");
            #endregion
        }
        
        #region Properties
        public UIForquickaccessplaceyText UIForquickaccessplaceyText
        {
            get
            {
                if ((this.mUIForquickaccessplaceyText == null))
                {
                    this.mUIForquickaccessplaceyText = new UIForquickaccessplaceyText(this);
                }
                return this.mUIForquickaccessplaceyText;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UINewTabGoogleChromeClient UINewTabGoogleChromeClient
        {
            get
            {
                if ((this.mUINewTabGoogleChromeClient == null))
                {
                    this.mUINewTabGoogleChromeClient = new UINewTabGoogleChromeClient(this);
                }
                return this.mUINewTabGoogleChromeClient;
            }
        }
        
        public WinWindow UIBingGoogleChromeWindow
        {
            get
            {
                if ((this.mUIBingGoogleChromeWindow == null))
                {
                    this.mUIBingGoogleChromeWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBingGoogleChromeWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Bing";
                    this.mUIBingGoogleChromeWindow.WindowTitles.Add("Bing - Google Chrome");
                    #endregion
                }
                return this.mUIBingGoogleChromeWindow;
            }
        }
        
        public WinWindow UIMicrosoftBingGoogleCWindow1
        {
            get
            {
                if ((this.mUIMicrosoftBingGoogleCWindow1 == null))
                {
                    this.mUIMicrosoftBingGoogleCWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIMicrosoftBingGoogleCWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "microsoft - Bing";
                    this.mUIMicrosoftBingGoogleCWindow1.WindowTitles.Add("microsoft - Bing - Google Chrome");
                    this.mUIMicrosoftBingGoogleCWindow1.WindowTitles.Add("Microsoft Store Online - Welcome - Google Chrome");
                    this.mUIMicrosoftBingGoogleCWindow1.WindowTitles.Add("Xbox: Xbox One and Xbox One S Consoles, Games & Accessories |-Microsoft Store - G" +
                            "oogle Chrome");
                    #endregion
                }
                return this.mUIMicrosoftBingGoogleCWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIForquickaccessplaceyText mUIForquickaccessplaceyText;
        
        private UIItemGroup mUIItemGroup;
        
        private UINewTabGoogleChromeClient mUINewTabGoogleChromeClient;
        
        private WinWindow mUIBingGoogleChromeWindow;
        
        private WinWindow mUIMicrosoftBingGoogleCWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIForquickaccessplaceyText : WinText
    {
        
        public UIForquickaccessplaceyText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinText.PropertyNames.Name] = "For quick access, place your bookmarks here on the bookmarks bar.";
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinHyperlink UIImportbookmarksnowHyperlink
        {
            get
            {
                if ((this.mUIImportbookmarksnowHyperlink == null))
                {
                    this.mUIImportbookmarksnowHyperlink = new WinHyperlink(this);
                    #region Search Criteria
                    this.mUIImportbookmarksnowHyperlink.SearchProperties[WinHyperlink.PropertyNames.Name] = "Import bookmarks now…";
                    this.mUIImportbookmarksnowHyperlink.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIImportbookmarksnowHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WinHyperlink mUIImportbookmarksnowHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINewTabGoogleChromeClient : WinClient
    {
        
        public UINewTabGoogleChromeClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinToolBar UIBookmarksToolBar
        {
            get
            {
                if ((this.mUIBookmarksToolBar == null))
                {
                    this.mUIBookmarksToolBar = new WinToolBar(this);
                    #region Search Criteria
                    this.mUIBookmarksToolBar.SearchProperties[WinToolBar.PropertyNames.Name] = "Bookmarks";
                    this.mUIBookmarksToolBar.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIBookmarksToolBar;
            }
        }
        #endregion
        
        #region Fields
        private WinToolBar mUIBookmarksToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMercuryHealthMercuryWindow : WinWindow
    {
        
        public UIMercuryHealthMercuryWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Mercury Health - Mercury Health - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Mercury Health - Mercury Health - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UIMercuryHealthMercuryWindow1
        {
            get
            {
                if ((this.mUIMercuryHealthMercuryWindow1 == null))
                {
                    this.mUIMercuryHealthMercuryWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIMercuryHealthMercuryWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Mercury Health - Mercury Health";
                    this.mUIMercuryHealthMercuryWindow1.WindowTitles.Add("Mercury Health - Mercury Health - Google Chrome");
                    #endregion
                }
                return this.mUIMercuryHealthMercuryWindow1;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIMercuryHealthMercuryWindow1;
        #endregion
    }
}
